# Form implementation generated from reading ui file 'designer/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.serialPortsGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.serialPortsGroupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.serialPortsGroupBox.setObjectName("serialPortsGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.serialPortsGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.serialPortsComboBox = QtWidgets.QComboBox(parent=self.serialPortsGroupBox)
        self.serialPortsComboBox.setObjectName("serialPortsComboBox")
        self.horizontalLayout_2.addWidget(self.serialPortsComboBox)
        self.rescanSerialPortsButton = QtWidgets.QPushButton(
            parent=self.serialPortsGroupBox
        )
        self.rescanSerialPortsButton.setObjectName("rescanSerialPortsButton")
        self.horizontalLayout_2.addWidget(self.rescanSerialPortsButton)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.serialPortsGroupBox)
        self.channelsGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.channelsGroupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.channelsGroupBox.setObjectName("channelsGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.channelsGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ch16RadioButton = QtWidgets.QRadioButton(parent=self.channelsGroupBox)
        self.ch16RadioButton.setChecked(True)
        self.ch16RadioButton.setObjectName("ch16RadioButton")
        self.verticalLayout_2.addWidget(self.ch16RadioButton)
        self.ch32RadioButton = QtWidgets.QRadioButton(parent=self.channelsGroupBox)
        self.ch32RadioButton.setCheckable(True)
        self.ch32RadioButton.setObjectName("ch32RadioButton")
        self.verticalLayout_2.addWidget(self.ch32RadioButton)
        self.ch64RadioButton = QtWidgets.QRadioButton(parent=self.channelsGroupBox)
        self.ch64RadioButton.setCheckable(True)
        self.ch64RadioButton.setObjectName("ch64RadioButton")
        self.verticalLayout_2.addWidget(self.ch64RadioButton)
        self.verticalLayout.addWidget(self.channelsGroupBox)
        self.experimentGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.experimentGroupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.experimentGroupBox.setCheckable(True)
        self.experimentGroupBox.setChecked(False)
        self.experimentGroupBox.setObjectName("experimentGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.experimentGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.experimentGroupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.experimentTextField = QtWidgets.QLineEdit(parent=self.experimentGroupBox)
        self.experimentTextField.setObjectName("experimentTextField")
        self.gridLayout.addWidget(self.experimentTextField, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.experimentGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.browseJSONButton = QtWidgets.QPushButton(parent=self.experimentGroupBox)
        self.browseJSONButton.setObjectName("browseJSONButton")
        self.gridLayout.addWidget(self.browseJSONButton, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.JSONLabel = QtWidgets.QLabel(parent=self.experimentGroupBox)
        self.JSONLabel.setText("")
        self.JSONLabel.setObjectName("JSONLabel")
        self.verticalLayout_3.addWidget(self.JSONLabel)
        self.verticalLayout.addWidget(self.experimentGroupBox)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.startAcquisitionButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startAcquisitionButton.setObjectName("startAcquisitionButton")
        self.horizontalLayout_5.addWidget(self.startAcquisitionButton)
        self.stopAcquisitionButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stopAcquisitionButton.setObjectName("stopAcquisitionButton")
        self.horizontalLayout_5.addWidget(self.stopAcquisitionButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.graphWidget = PlotWidget(parent=self.centralwidget)
        self.graphWidget.setObjectName("graphWidget")
        self.horizontalLayout.addWidget(self.graphWidget)
        self.horizontalLayout.setStretch(1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "sEMG Acquisition GUI"))
        self.serialPortsGroupBox.setTitle(_translate("MainWindow", "Serial port"))
        self.serialPortsComboBox.setToolTip(
            _translate("MainWindow", "List of available serial ports")
        )
        self.rescanSerialPortsButton.setToolTip(
            _translate("MainWindow", "Refresh list of available serial ports")
        )
        self.rescanSerialPortsButton.setText(_translate("MainWindow", "Rescan"))
        self.channelsGroupBox.setTitle(_translate("MainWindow", "Channels"))
        self.ch16RadioButton.setText(_translate("MainWindow", "16"))
        self.ch32RadioButton.setText(_translate("MainWindow", "32"))
        self.ch64RadioButton.setText(_translate("MainWindow", "64"))
        self.experimentGroupBox.setTitle(
            _translate("MainWindow", "Configure experiment")
        )
        self.label.setText(_translate("MainWindow", "Output file name:"))
        self.experimentTextField.setToolTip(
            _translate(
                "MainWindow",
                "If no name is provided, one based on the timestamp will be used",
            )
        )
        self.label_2.setText(_translate("MainWindow", "JSON with configuration:"))
        self.browseJSONButton.setText(_translate("MainWindow", "Browse"))
        self.startAcquisitionButton.setText(
            _translate("MainWindow", "Start acquisition")
        )
        self.stopAcquisitionButton.setText(_translate("MainWindow", "Stop acquisition"))


from pyqtgraph import PlotWidget
